/*
 * lucinate
 *
 * (c) Harminder Virk
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { dirname } from 'node:path'
import { EventEmitter } from 'node:events'
import { writeFile, mkdir } from 'node:fs/promises'
import { type Application } from '../../shims/runtime/app.js'
import { RuntimeException } from '../../shims/runtime/exceptions.js'

import { OrmSchemaBuilder } from './builder.js'
import type { Database } from '../../database/main.js'
import { type QueryClientContract } from '../../types/database.js'
import type { OrmSchemaGeneratorConfig, DatabaseColumn, SchemaRules } from '../../types/schema_generator.js'

/**
 * OrmSchemaGenerator orchestrates the process of generating TypeScript
 * model schemas from database tables.
 */
export class OrmSchemaGenerator extends EventEmitter<{
  /**
   * Emitted when tables are collected from the database
   */
  'collect:tables': [tables: string[]]

  /**
   * Emitted for each table with its column information
   */
  'table:info': [info: { tableName: string; columns: Record<string, DatabaseColumn> }]

  /**
   * Emitted when schema generation starts
   */
  'generating:schema': []
}> {
  /**
   * Schema builder instance
   */
  private builder: OrmSchemaBuilder

  /**
   * Query client instance
   */
  private connection: QueryClientContract

  constructor(
    private db: Database,
    private application: Application<any>,
    private config: OrmSchemaGeneratorConfig
  ) {
    super()
    const connectionName = this.config.connectionName || this.db.primaryConnectionName
    this.connection = this.db.connection(connectionName)
    this.builder = new OrmSchemaBuilder(this.connection)
  }

  /**
   * Load schema rules from the configured paths
   */
  private async loadSchemaRules(): Promise<void> {
    if (!this.config.rulesPaths || this.config.rulesPaths.length === 0) {
      return
    }

    try {
      const rules = await Promise.all(
        this.config.rulesPaths.map((rulesPath) => {
          return this.application.importDefault(rulesPath)
        })
      )
      this.builder.loadRules(rules as SchemaRules[])
    } catch (error) {
      throw new RuntimeException('Failed to load schema rules', {
        cause: error,
      })
    }
  }

  /**
   * Fetch all tables and their columns from the database
   */
  private async fetchTablesAndColumns(): Promise<
    Array<{ name: string; columns: Record<string, any>; primaryKeys: string[] }>
  > {
    /**
     * Get list of all tables from the database
     */
    let tables = await this.connection.getAllTablesWithSchema(this.config.schemas)
    if (this.config.excludeTables) {
      tables = tables.filter(
        ({ name, schema }) =>
          !this.config.excludeTables?.includes(name) &&
          !(schema && this.config.excludeTables?.includes(`${schema}.${name}`))
      )
    }

    this.emit(
      'collect:tables',
      tables.map(({ name }) => name)
    )

    /**
     * Fetch columns and primary keys for each table
     */
    const tablesWithColumns = await Promise.all(
      tables.map(async ({ name, schema }) => {
        const tableLookup = schema ? `${schema}.${name}` : name
        const [columns, primaryKeys] = await Promise.all([
          this.connection.columnsInfo(name, undefined, schema),
          this.connection.getPrimaryKeys(tableLookup),
        ])

        this.emit('table:info', { tableName: name, columns })
        return { name, columns, primaryKeys }
      })
    )

    return tablesWithColumns
  }

  /**
   * Generate schemas and write to output file
   */
  async generate(): Promise<void> {
    /**
     * Load custom schema rules if provided
     */
    await this.loadSchemaRules()

    /**
     * Fetch all tables and columns
     */
    const tables = await this.fetchTablesAndColumns()

    /**
     * Generate schemas using the builder
     */
    this.emit('generating:schema')
    const schemas = this.builder.generateSchemas(tables)
    const output = this.builder.getOutput(schemas)

    /**
     * Write to output file
     */
    const outputDir = dirname(this.config.outputPath)
    await mkdir(outputDir, { recursive: true })
    const comment = [
      '/**',
      ' * This file is automatically generated',
      ' * DO NOT EDIT manually',
      ' * Re-run the schema generator to update this file',
      ' */',
    ].join('\n')
    await writeFile(this.config.outputPath, `${comment}\n\n${output}`, 'utf-8')
  }

  /**
   * Close database connections
   */
  async close() {
    await this.db.manager.closeAll(true)
  }
}
